export const FORM_VALIDATION = 'FORM_VALIDATION';
export const FORM_VALIDATION_SUCCESS = 'FORM_VALIDATION_SUCCESS';
export const FORM_VALIDATION_ERROR = 'FORM_VALIDATION_ERROR';

export const ADD_PRODUCT = 'ADD_PRODUCT_VALIDATION';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const BEGIN_LOADING_PRODUCTS = 'BEGIN_LOADING_PRODUCTS';
export const LOADING_PRODUCTS_SUCCESS = 'LOADING_PRODUCTS_SUCCESS';
export const LOADING_PRODUCTS_ERROR = 'LOADING_PRODUCTS_ERROR';


export const GET_DELETE_PRODUCT = 'GET_DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'ELETE_PRODUCT_ERROR';


export const GET_PRODUCT_UPDATE = 'GET_PRODUCT_UPDATE';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_ERROR = 'PRODUCT_UPDATE_ERROR';

export const BEGIN_PRODUCT_UPDATED = 'BEGIN_PRODUCT_UPDATED';
export const PRODUCT_UPDATED_SUCCESS = 'PRODUCT_UPDATED_SUCCESS';
export const PRODUCT_UPDATED_ERROR = 'PRODUCT_UPDATED_ERROR';